name: study_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.6
  date_picker_timeline: ^1.2.5
  device_preview: ^1.2.0
  file_picker: ^8.0.0+1
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_ml_model_downloader: ^0.3.0+21
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.3.1
  google_mlkit_text_recognition: ^0.12.0
  google_nav_bar: ^5.0.6
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  logger: ^2.4.0
  lottie: ^3.1.2
  provider: ^6.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+1
  translator: ^1.0.3+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/Logo_studyHub.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/Onboarding/
    - assets/images/
    - assets/logo/
    - assets/fonts/
