// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbw3XTzelNUaa4kl-BHK_NyHX_jH-ouWo',
    appId: '1:71200197554:web:85d7507596e7981e45f2ab',
    messagingSenderId: '71200197554',
    projectId: 'study-hub-75d4b',
    authDomain: 'study-hub-75d4b.firebaseapp.com',
    storageBucket: 'study-hub-75d4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKc1rKBHls6ERcY9u8LHZltYGKGVhph6g',
    appId: '1:71200197554:android:04beb5a215c066de45f2ab',
    messagingSenderId: '71200197554',
    projectId: 'study-hub-75d4b',
    storageBucket: 'study-hub-75d4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vUe7Otg9EDPBm8jZntdWpqIvvUINbH4',
    appId: '1:71200197554:ios:444786e62b2b179e45f2ab',
    messagingSenderId: '71200197554',
    projectId: 'study-hub-75d4b',
    storageBucket: 'study-hub-75d4b.firebasestorage.app',
    iosBundleId: 'com.example.studyHub',
  );
}
